version: '3'
services:
  php-app:
    image: php:apache
    container_name: php_app
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    restart: always
    environment:
      - DB_HOST=database-1.copsassmgk3b.us-east-1.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASSWORD=Test1234
      - DB_NAME=demo_project
