version: '3'
services:
  php-app:
    image: php:apache
    container_name: php_app
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    restart: always
    environment:
      - DB_HOST=<RDS-ENDPOINT>
      - DB_USER=<YOUR_DB_USERNAME>
      - DB_PASSWORD=<YOUR_DB_PASSWORD>
      - DB_NAME=<YOUR_DATABASE_NAME>
